# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saba < Formula
  desc "Declarative development framework saba"
  homepage "https://github.com/asweed888/saba"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/asweed888/saba/releases/download/v1.2.0/saba_1.2.0_darwin_arm64.tar.gz"
      sha256 "bda4a3e07edf7a8bd4635f640a06a3fc86ec9544c205e6266fac8a50c440c345"

      def install
        bin.install "saba"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/asweed888/saba/releases/download/v1.2.0/saba_1.2.0_darwin_amd64.tar.gz"
      sha256 "b3e9fd7153aafeb6ab066a81e6f9a7b2dac585dabe083d2f6d1ee206033e478e"

      def install
        bin.install "saba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/asweed888/saba/releases/download/v1.2.0/saba_1.2.0_linux_amd64.tar.gz"
      sha256 "295bf36911f402c321b8df5b6e2710163595118cbe198e664f414caaaeb99075"

      def install
        bin.install "saba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/saba/releases/download/v1.2.0/saba_1.2.0_linux_arm64.tar.gz"
      sha256 "61c32f88778f056e942d31d59d8c71e320c34014bd86d2a29325c3b882c70195"

      def install
        bin.install "saba"
      end
    end
  end
end
