# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saba < Formula
  desc "Declarative development framework saba"
  homepage "https://github.com/asweed888/saba"
  version "1.0.4"

  on_macos do
    url "https://github.com/asweed888/saba/releases/download/v1.0.4/saba_darwin_all.tar.gz"
    sha256 "4216845770f3f494df156a79a806732405be275fc3447e7d2bf8b8f20619432f"

    def install
      bin.install "saba"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/saba/releases/download/v1.0.4/saba_linux_armv6.tar.gz"
      sha256 "28017b9708fd058cb4769250e77a89eb94458b0d28fd57440a833f3da954e7d0"

      def install
        bin.install "saba"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/asweed888/saba/releases/download/v1.0.4/saba_linux_x86_64.tar.gz"
      sha256 "6f3eec563d6fd51774aff513ecc97548f1b78d94dbd16577112c9f069335730c"

      def install
        bin.install "saba"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/saba/releases/download/v1.0.4/saba_linux_arm64.tar.gz"
      sha256 "11b76284e4a1e907452275a230bc874984d375b4ac4554a4318ffa090ba55fe1"

      def install
        bin.install "saba"
      end
    end
  end

  test do
    system "#{bin}/saba help"
  end
end
